name: Run Ubuntu Container on Self-Hosted Runner

on:
  push:
    branches:
      - main  # Runs on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting `main`

jobs:
  run-container:
    name: Run Ubuntu Container
    runs-on: self-hosted  # Use the self-hosted runner
    labels: [runnerv1]    # Ensure the runner matches this label

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Start Docker Service
        run: |
          echo "Ensuring Docker is installed and running..."
          docker --version

      # Step 3: Run an Ubuntu container
      - name: Run Ubuntu Container
        run: |
          docker run --rm -it ubuntu:latest /bin/bash -c "
          echo 'Hello from Ubuntu container';
          apt-get update && apt-get install -y curl;
          echo 'Installation complete';"
